USE [Teste]
GO
IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE UPPER(TABLE_NAME) = UPPER('NOTAFISCALITEM') 
            AND  UPPER(COLUMN_NAME) = UPPER('BaseIpi'))
BEGIN
	ALTER TABLE NOTAFISCALITEM ADD BaseIpi Decimal(18,5) NULL;
END

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE UPPER(TABLE_NAME) = UPPER('NOTAFISCALITEM') 
            AND  UPPER(COLUMN_NAME) = UPPER('ValorIpi'))
BEGIN
	ALTER TABLE NOTAFISCALITEM ADD ValorIpi Decimal(18,5) NULL;
END

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE UPPER(TABLE_NAME) = UPPER('NOTAFISCALITEM') 
            AND  UPPER(COLUMN_NAME) = UPPER('AliquotaIpi'))
BEGIN
	ALTER TABLE NOTAFISCALITEM ADD AliquotaIpi Decimal(18,5) NULL;
END