USE [Teste]
GO
IF OBJECT_ID('dbo.PR_CONS_ICMS_IPI_NOTA_FISCAL') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.PR_CONS_ICMS_IPI_NOTA_FISCAL
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE PR_CONS_ICMS_IPI_NOTA_FISCAL
AS
BEGIN
	
	 SELECT 
		 Cfop
		,BaseIcms
		,SUM(ValorIcms) AS VALORICMS
		,SUM(ValorIpi)	AS VALORIPI
		,BaseIpi
	FROM 
		NOTAFISCALITEM (NOLOCK)
	GROUP BY 
		 Cfop,BaseIcms,BaseIpi
		

	 
	  
END
GO
GRANT EXECUTE ON dbo.P_NOTA_FISCAL_ITEM TO [public]
go
